name: Structural Time Series
description: California electricity demand forecasting with Prophet.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2020-10-14"
api_version: 1

runtimes:
  - editor: Workbench
    kernel: Python 3.7
    edition: Standard
    version: 2021.09

engine_images:
  - image_name: engine
    tags:
      - 14-cml-2021.05-1

environment_variables:
  EIA_API_KEY:
    default: ""
    description: "Optional EIA open data API key"
    prompt_user: false

tasks:
  - type: run_session
    name: Install Dependencies
    script: cml/install_dependencies.py
    cpu: 2
    memory: 4
    short_summary: Install project dependencies.
    kernel: python3

  - type: create_job
    name: Launch Parallel Model Fitting
    entity_label: fit_models_parallel
    script: cml/fit_models_parallel.py
    arguments: None
    short_summary: Create job to launch parallel training script execution.
    long_summary: Creates job to launch independent training workloads for each forecast script in the /scripts directory.
    cpu: 1
    memory: 2
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3

  - type: run_job
    entity_label: fit_models_parallel
    short_summary: Running job to train forecasts in parallel.
    long_summary: Running job to train forecasts in parallel via CDSW Workers API

  - type: start_application
    name: Diagnostic App
    subdomain: diagnostics
    script: apps/launch_diagnostics.py
    short_summary: Starting forecast diagnostics application
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3

  - type: start_application
    name: Forecast App
    subdomain: forecast
    script: apps/launch_forecast.py
    short_summary: Starting primary forecast application
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
